<a href="https://colab.research.google.com/github/swatidhote/EDA_Optimising_NYC_Taxis_-swati-dhote-/blob/main/01_NumPy_arrays_and_basic_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let's import the NumPy library

In [2]:
import numpy as np

Let's creating an empty NumPy array

In [3]:
# empty_array = np.array()

In [4]:
empty_array = np.array(object = [])

In [5]:
# By default, unless specified or dictated by the data type, NumPy resorts to making a float64 array
# This has benefits because float64 can handle most numeric data types, and NumPy is primarily used for mathematical calculations
empty_array

array([], dtype=float64)

In [6]:
type(empty_array)  # data type of variable

numpy.ndarray

In [7]:
empty_array.dtype  # data type of elements

dtype('float64')

In [8]:
empty_array.ndim  # number of dimensions

1

In [9]:
empty_array.shape  # shape of the array

(0,)

In [10]:
empty_array.size  # size of the array; counts all elements across dimensions

0

Let's creating NumPy arrays with elements

In [11]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

In [12]:
type(my_array)

numpy.ndarray

In [13]:
my_array.dtype

dtype('int64')

In [14]:
my_array.ndim

1

In [15]:
my_array.shape

(3,)

In [16]:
my_array.size

3

In [17]:
my_array = np.array([1.5, 2, 3])  # arrays with different data types are automatically typecast if possible
my_array

array([1.5, 2. , 3. ])

In [18]:
my_array.dtype

dtype('float64')

In [19]:
my_array = np.array(['yes', 'no', 'maybe'])
my_array

array(['yes', 'no', 'maybe'], dtype='<U5')

In [20]:
my_array.dtype  # unicode string datatype of length 5

dtype('<U5')

Here are some more ways to create NumPy arrays

In [21]:
# other ways to create arrays
np.arange(start = 1, stop = 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.array(range(1, 10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(start = 1, stop = 10, step = 2)  # np.arange() supports steps

array([1, 3, 5, 7, 9])

In [24]:
np.arange(-2, 10, 3)

array([-2,  1,  4,  7])

In [25]:
np.arange(10, 16)

array([10, 11, 12, 13, 14, 15])

In [26]:
np.zeros(shape = 10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(2)

array([0., 0.])

In [28]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.zeros(shape = 10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones(shape = 5, dtype = 'int')

array([1, 1, 1, 1, 1])

In [32]:
np.linspace(start = 2, stop = 3, num = 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [33]:
np.linspace(1, -5, 20)

array([ 1.        ,  0.68421053,  0.36842105,  0.05263158, -0.26315789,
       -0.57894737, -0.89473684, -1.21052632, -1.52631579, -1.84210526,
       -2.15789474, -2.47368421, -2.78947368, -3.10526316, -3.42105263,
       -3.73684211, -4.05263158, -4.36842105, -4.68421053, -5.        ])

We can create multidimensional NumPy arrays

In [34]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
type(matrix)

numpy.ndarray

In [36]:
matrix.dtype

dtype('int64')

In [37]:
matrix.ndim

2

In [38]:
matrix.shape

(3, 3)

In [39]:
matrix.size

9

In [40]:
# np.array([[1, 2, 3], [4, 5], [6, 7, 8, 9]])  # NumPy arrays need to have the same number of elements in a single dimension

In [41]:
three_tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
three_tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
type(three_tensor)

numpy.ndarray

In [43]:
three_tensor.dtype

dtype('int64')

In [44]:
three_tensor.ndim

3

In [45]:
three_tensor.shape

(2, 2, 2)

In [46]:
three_tensor.size

8