<a href="https://colab.research.google.com/github/swatidhote/EDA_Optimising_NYC_Taxis_-swati-dhote-/blob/main/04_NumPy_array_manipulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let's import the NumPy library

In [ ]:
import numpy as np

Let's add and remove elements from NumPy arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# arr.append(6)

In [ ]:
arr = np.append(arr = arr, values = 6)  # append 6 to the end of the array
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = np.delete(arr = arr, obj = 4)  # delete the element at index 4
arr

array([1, 2, 3, 4, 6])

In [ ]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat2 = np.append(mat, [10, 11, 12])
mat2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
mat3 = np.append(mat, [[10, 11, 12]])
mat3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
mat4 = np.append(mat, [[10, 11, 12]], axis = 0)
mat4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# mat5 = np.append(mat, [10, 11, 12], axis = 1)

In [ ]:
mat5 = np.append(mat, [[10], [11], [12]], axis = 1)
mat5

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [ ]:
mat6 = np.delete(mat, 1)
mat6

array([1, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mat7 = np.delete(mat, 1, axis = 0)
mat7

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
mat8 = np.delete(mat, 1, axis = 1)
mat8

array([[1, 3],
       [4, 6],
       [7, 9]])

We can join (concatenate) multiple NumPy arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

In [ ]:
# np.concatenate(arr1, arr2)  # np.concatenate() accepts a sequence of arrays as its input

In [ ]:
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((arr1, arr2, arr3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6]])

In [ ]:
np.concatenate((mat1, mat2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((mat1, mat2), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# np.concatenate((mat1, mat2), axis = 1)  # cannot concatenate the 1D array to the 2nd (column) dimension

In [ ]:
mat3 = np.array([[7], [8]])

In [ ]:
# np.concatenate((mat1, mat3), axis = 0)  # cannot concatenate as dimensions do not match

In [ ]:
np.concatenate((mat1, mat3), axis = 1)

array([[1, 2, 7],
       [3, 4, 8]])